development:
  adapter: solr
  url: <%= ENV['SOLR_TEST_URL'] || raise("SOLR_TEST_URL not set") %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_TEST_URL'] || raise("SOLR_TEST_URL not set") %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://your.production.server:8080/bl_solr/core0" %>
