development:
  archivist:
    - archivist1@example.test
  admin:
    - dev@example.test
test:
  archivist:
    - archivist1@example.test
  admin:
    - dev@example.test

production:
  # Add roles for users here.
