development:
  archivist:
    - archivist1@example.test
  admin:
    - dev@test.internal
test:
  archivist:
    - archivist1@example.test
  admin:
    - dev@test.internal

production:
  # Add roles for users here.
