# This is a sample config file that points to a solr server for each environment
development:
  url: <%= ENV['SOLR_URL'] || raise("SOLR_URL not set") %>
test:
  url: <%= ENV['SOLR_TEST_URL'] || raise("SOLR_TEST_URL not set") %>
production:
  url: <%= ENV['SOLR_URL'] || "http://your.production.server:8080/bl_solr/core0" %>
